name: publish-release

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'CHANGELOG.md'
on:
  push:

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: get-the-latest-version
      id: latest
      uses: miniscruff/changie-action@v2
      with:
        version: latest
        args: latest

    - name: create-tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        custom_tag: ${{ steps.latest.outputs.output }}
        github_token: ${{ env.GITHUB_TOKEN }}

    - name: build
      run: |
        make build-in-docker APP_VERSION=${{ steps.latest.outputs.output }}

    - name: create-github-release
      uses: softprops/action-gh-release@v1
      with:
        body_path: .changes/${{ steps.latest.outputs.output }}.md
        files: bin/ydbops*
        tag_name: ${{ steps.latest.outputs.output }} 
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
