# Implicit requirements
# runner must have `docker` and `curl` installed (true on github-runners)

name: run-lint


on:
  workflow_call:

jobs:
  smart-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-when-fork-source
        uses: actions/checkout@v3
        if: github.event.pull_request.head.sha != ''
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - name: checkout-when-this-repo-source
        uses: actions/checkout@v3
        if: github.event.pull_request.head.sha == ''
  lint:
    concurrency:
      group: lint-golangci-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - smart-checkout
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: set-env-vars
        run: |
          echo "HOME=/actions-runner" >> $GITHUB_ENV
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.48.0
  code-format-check:
    concurrency:
      group: lint-autoformat-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - smart-checkout
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: set-env-vars
        run: |
          echo "HOME=/actions-runner" >> $GITHUB_ENV
      - name: Install utilities
        run: |
          go install mvdan.cc/gofumpt@v0.3.1
          go install github.com/rinchsan/gosimports/cmd/gosimports@v0.1.5
      - name: format all files with auto-formatter
        run: bash ./.github/scripts/format-all-go-code.sh "$PWD"
      - name: Check repository diff
        run: bash ./.github/scripts/check-work-copy-equals-to-committed.sh "auto-format broken"
